apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  annotations:
  name: discounts
  namespace: east-travel-agency
spec:
  hosts:
  - discounts.east-travel-agency.svc.cluster.local
  http:
  - route:
    - destination:
        host: discounts.travel-agency.svc.west-mesh-imports.local
      weight: 75
    - destination:
        host: discounts.east-travel-agency.svc.cluster.local
      weight: 25
